server:
  port: ${TELEGRAM_BOT_PORT}
bot:
  name: ExploreWithMeBot
  token: ${EXPLORE_WITH_ME_BOT_TOKEN}
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/telegram_users
    username: root
    password: root
server:
  port: 7070