CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    name  VARCHAR(200) NOT NULL
);

CREATE INDEX IF NOT EXISTS users_index ON users (email, name);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS compilations_index ON compilations (title, pinned);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS categories_index ON categories (name);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR     NOT NULL UNIQUE,
    annotation         VARCHAR     NOT NULL,
    description        VARCHAR     NOT NULL,
    event_date         TIMESTAMPTZ NOT NULL,
    initiator_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created_on         TIMESTAMPTZ NOT NULL,
    published_on       TIMESTAMPTZ,
    category_id        BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    state              VARCHAR     NOT NULL,
    paid               BOOLEAN     NOT NULL,
    request_moderation BOOLEAN     NOT NULL,
    participant_limit  INT         NOT NULL DEFAULT 0,
    confirmed_requests BIGINT      NOT NULL DEFAULT 0,
    lat                FLOAT       NOT NULL,
    lon                FLOAT       NOT NULL,
    views              BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS events_index ON events (title, annotation, paid, category_id, event_date);